[2021-07-25 00:05:45,872] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:07:01,092] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:07:01,287] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:07:01,500] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:07:01,948] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:07:17,012] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:07:17,159] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:07:17,350] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:07:17,644] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:07:19,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:07:19,823] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:07:20,018] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:07:20,279] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:07:33,559] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:07:33,706] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:07:33,890] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:07:34,150] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:09:08,446] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:09:10,353] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:11:23,326] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:11:25,280] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:11:50,851] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:11:53,218] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:11:55,865] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:11:57,398] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 462120
[2021-07-25 00:11:57,549] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:12:12,829] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:12:12,980] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:12:13,199] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:12:13,485] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:12:41,034] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:12:43,176] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:12:44,221] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:12:45,718] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461528
[2021-07-25 00:12:45,874] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:12:59,171] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461382
[2021-07-25 00:12:59,323] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:13:08,209] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:13:08,352] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:13:08,559] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:13:08,817] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:13:11,261] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:13:11,402] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:13:11,600] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:13:11,871] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:15:25,515] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:15:27,607] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:15:31,024] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:15:32,397] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 459892
[2021-07-25 00:15:32,561] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:15:52,788] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 459598
[2021-07-25 00:15:52,936] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:16:07,764] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:16:10,136] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:16:14,646] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461382
[2021-07-25 00:16:14,788] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:16:24,691] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:16:24,830] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:16:25,028] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:16:25,337] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:16:30,726] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:18:18,386] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:18:19,681] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461528
[2021-07-25 00:18:19,835] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:18:30,821] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461382
[2021-07-25 00:18:30,970] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:18:51,391] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:18:51,535] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:18:51,736] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:18:52,005] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:25:42,445] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:25:44,713] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:25:53,864] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 460956
[2021-07-25 00:25:54,022] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:26:00,661] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 72
[2021-07-25 00:26:43,131] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:26:45,441] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:26:48,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 460810
[2021-07-25 00:26:48,245] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:26:58,122] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 52
[2021-07-25 00:27:31,656] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 460810
[2021-07-25 00:27:31,809] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:28:39,494] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:28:41,757] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:28:46,435] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 52
[2021-07-25 00:29:01,849] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 460810
[2021-07-25 00:29:02,014] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:29:07,990] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 52
[2021-07-25 00:29:34,128] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:29:36,301] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:29:41,513] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 460810
[2021-07-25 00:29:41,665] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:29:48,580] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 52
[2021-07-25 00:30:36,081] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:30:38,089] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:30:44,478] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/organization/ HTTP/1.1" 200 104655
[2021-07-25 00:30:44,633] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:30:47,462] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461382
[2021-07-25 00:30:47,609] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:30:53,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/None HTTP/1.1" 301 0
[2021-07-25 00:30:53,752] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/ HTTP/1.1" 302 0
[2021-07-25 00:30:53,951] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/None/change/ HTTP/1.1" 302 0
[2021-07-25 00:30:54,223] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:35:22,882] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:35:24,902] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:35:29,073] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 00:35:30,567] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461546
[2021-07-25 00:35:30,722] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:35:39,394] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:35:41,574] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:35:41,731] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:35:49,262] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:35:51,517] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:35:51,684] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:35:56,326] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 52
[2021-07-25 00:36:01,037] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 52
[2021-07-25 00:37:10,033] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:37:12,141] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:37:49,864] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:37:51,952] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:37:58,192] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:38:00,735] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:38:00,923] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:38:17,234] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:38:19,497] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:38:19,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:38:39,707] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:38:41,856] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:38:46,621] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 74, in layer_input
    print(post['name'])
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'name'
[2021-07-25 00:38:46,629] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 86367
[2021-07-25 00:38:47,589] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 74, in layer_input
    print(post['name'])
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'name'
[2021-07-25 00:38:47,591] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 86367
[2021-07-25 00:38:50,645] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 74, in layer_input
    print(post['name'])
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'name'
[2021-07-25 00:38:50,648] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 86367
[2021-07-25 00:39:09,271] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:39:11,597] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:39:15,040] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:39:17,558] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:39:17,718] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:39:54,821] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:39:56,869] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:40:00,563] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 74, in layer_input
    print(post.get['type'])
TypeError: 'method' object is not subscriptable
[2021-07-25 00:40:00,565] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 77950
[2021-07-25 00:40:19,656] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:40:21,761] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:40:22,885] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:40:25,341] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:40:25,503] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:40:45,710] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:40:47,798] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:40:51,697] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:40:54,208] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:40:54,367] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:42:50,714] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:42:52,951] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:47:58,346] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:48:00,406] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:48:05,890] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 75, in layer_input
    print(queryset.Owner)
AttributeError: 'QuerySet' object has no attribute 'Owner'
[2021-07-25 00:48:05,893] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 77958
[2021-07-25 00:48:21,002] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:48:22,915] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:48:25,872] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:48:29,228] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:48:29,404] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:49:46,605] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:49:48,730] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:49:55,992] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:49:58,399] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:49:58,557] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:50:33,304] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:50:35,425] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:50:42,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:50:45,161] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:50:45,353] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:50:55,832] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/organization/ HTTP/1.1" 200 104655
[2021-07-25 00:50:55,986] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:50:57,810] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:50:57,953] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:51:16,757] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:51:18,903] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:51:22,364] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 76, in layer_input
    print(qs.id+'我被选中了'+qs.Owner)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[2021-07-25 00:51:22,366] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 78376
[2021-07-25 00:51:23,618] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 76, in layer_input
    print(qs.id+'我被选中了'+qs.Owner)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[2021-07-25 00:51:23,621] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 78376
[2021-07-25 00:51:39,723] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:51:42,193] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:51:42,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 00:51:45,521] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 00:51:45,674] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 00:53:30,311] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:53:32,399] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:54:01,782] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:54:02,710] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:54:19,500] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:54:21,494] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:55:24,854] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:55:25,822] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:56:26,935] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:56:28,943] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:57:22,413] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:57:24,575] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:57:31,525] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:57:33,594] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:57:39,949] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 76, in layer_input
    Oblist.objects(id=qs.id).update(Owner=post['type'])
TypeError: 'Manager' object is not callable
[2021-07-25 00:57:39,953] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 78178
[2021-07-25 00:59:47,316] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 00:59:49,419] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 00:59:51,974] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/ajax
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\simpleui\admin.py", line 20, in callback
    return func(self, request, queryset)
  File "E:\djangoProject\crm\admin.py", line 76, in layer_input
    self.model.objects(id=qs.id).update(Owner=post['type'])
TypeError: 'Manager' object is not callable
[2021-07-25 00:59:51,977] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /admin/crm/oblist/ajax HTTP/1.1" 500 78318
[2021-07-25 01:01:36,008] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 01:01:38,243] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 01:01:44,018] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 01:01:46,569] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:01:46,733] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:02:03,397] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 01:02:05,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:02:05,882] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:02:15,538] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 01:02:17,798] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:02:17,955] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:02:27,358] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 01:02:29,560] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:02:29,716] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:03:41,812] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 01:03:43,923] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 01:05:10,969] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 01:05:12,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:05:12,635] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:09:24,021] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 01:09:26,351] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 01:09:45,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/logout/ HTTP/1.1" 200 161
[2021-07-25 01:09:45,339] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4071
[2021-07-25 01:09:52,943] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/ HTTP/1.1" 302 0
[2021-07-25 01:09:53,398] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 21071
[2021-07-25 01:09:56,478] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 420793
[2021-07-25 01:09:56,629] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:10:07,164] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 120
[2021-07-25 01:10:15,230] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/logout/ HTTP/1.1" 200 161
[2021-07-25 01:10:15,303] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4071
[2021-07-25 01:10:21,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/ HTTP/1.1" 302 0
[2021-07-25 01:10:21,820] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 01:10:25,139] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:10:25,292] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 01:10:33,992] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ajax HTTP/1.1" 200 62
[2021-07-25 01:10:36,259] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461400
[2021-07-25 01:10:36,430] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:14:24,836] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:14:26,809] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:16:46,992] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:16:47,946] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:18:41,753] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:18:43,846] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:19:06,135] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:19:08,152] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:19:16,959] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 12:19:18,404] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461577
[2021-07-25 12:19:18,416] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-25 12:19:18,569] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:19:23,307] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/import/ HTTP/1.1" 200 6289
[2021-07-25 12:19:23,337] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/import_export/import.css HTTP/1.1" 200 1376
[2021-07-25 12:20:37,864] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/import/ HTTP/1.1" 200 405310
[2021-07-25 12:20:55,546] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/import/ HTTP/1.1" 200 6289
[2021-07-25 12:20:59,349] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461577
[2021-07-25 12:21:04,829] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 52658)

[2021-07-25 12:21:04,885] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 302 0
[2021-07-25 12:21:06,085] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461636
[2021-07-25 12:21:06,278] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:21:15,335] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 52659)

[2021-07-25 12:21:15,439] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 302 0
[2021-07-25 12:21:16,613] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461636
[2021-07-25 12:21:16,770] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:22:20,855] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:22:23,016] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:22:26,830] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 302 0
[2021-07-25 12:22:26,954] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 52866)

[2021-07-25 12:22:28,432] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461636
[2021-07-25 12:22:28,616] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:23:01,403] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:23:03,484] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:23:29,209] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:23:31,200] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:23:32,525] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/export/? HTTP/1.1" 200 5827
[2021-07-25 12:23:37,726] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/export/? HTTP/1.1" 200 68896
[2021-07-25 12:24:48,711] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461577
[2021-07-25 12:25:01,538] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/?Owner__exact=%E8%80%BF%E8%90%8C%E8%90%8C HTTP/1.1" 200 467891
[2021-07-25 12:25:01,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:25:03,701] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/export/?Owner__exact=%E8%80%BF%E8%90%8C%E8%90%8C HTTP/1.1" 200 5827
[2021-07-25 12:25:08,146] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/export/?Owner__exact=%E8%80%BF%E8%90%8C%E8%90%8C HTTP/1.1" 200 11473
[2021-07-25 12:26:01,418] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461577
[2021-07-25 12:26:01,569] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:26:30,562] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-25 12:26:32,653] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 12:26:36,933] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 12:26:38,385] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 461577
[2021-07-25 12:26:38,547] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:26:46,249] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/?Campaign=%E6%B5%8B%E8%AF%95 HTTP/1.1" 200 292271
[2021-07-25 12:26:46,423] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-25 12:26:48,310] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/export/?Campaign=%E6%B5%8B%E8%AF%95 HTTP/1.1" 200 5827
[2021-07-25 12:26:54,149] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/export/?Campaign=%E6%B5%8B%E8%AF%95 HTTP/1.1" 200 5061
[2021-07-25 13:33:44,716] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-07-25 13:33:46,872] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:34:40,958] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:35:03,352] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:35:35,030] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:35:37,029] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:35:41,157] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23175
[2021-07-25 13:35:54,078] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:35:56,202] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:36:12,939] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:36:14,949] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:36:26,494] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-25 13:36:26,495] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-25 13:36:26,967] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-25 13:36:26,968] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-25 13:36:28,839] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 43, in index
    return HttpResponse(c.render_embed())
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 74, in render_embed
    return engine.render_embed(self, template_name, env, **kwargs)
  File "D:\Python39\lib\site-packages\pyecharts\render\engine.py", line 80, in render_embed
    return RenderEngine(env).render_chart_to_template(
  File "D:\Python39\lib\site-packages\pyecharts\render\engine.py", line 58, in render_chart_to_template
    tpl = self.env.get_template(template_name)
  File "D:\Python39\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "D:\Python39\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Python39\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "D:\Python39\lib\site-packages\jinja2\loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: simple_chart.html
[2021-07-25 13:36:28,842] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 98434
[2021-07-25 13:36:54,453] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:36:56,510] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:36:57,679] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5418
[2021-07-25 13:39:17,957] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:39:20,048] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:39:23,655] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 13:41:50,908] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 13:41:51,437] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:41:53,775] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:41:57,129] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 13:44:55,022] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:44:57,026] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:44:57,848] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5071
[2021-07-25 13:45:45,343] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:45:47,506] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:45:48,224] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5321
[2021-07-25 13:45:58,323] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:46:00,434] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:46:01,792] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 38, in index
    .add_xaxis(OWNERS.choices.value)
AttributeError: 'list' object has no attribute 'value'
[2021-07-25 13:46:01,795] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 68829
[2021-07-25 13:46:24,871] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:46:26,847] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:46:30,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5321
[2021-07-25 13:47:52,744] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-25 13:47:54,802] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:47:59,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5291
[2021-07-25 13:48:24,907] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-25 13:48:27,079] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:49:41,325] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:49:43,718] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:49:47,204] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 38, in index
    .add_xaxis(OWNERS.choices.display)
AttributeError: 'list' object has no attribute 'display'
[2021-07-25 13:49:47,206] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 68841
[2021-07-25 13:50:00,449] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:50:02,471] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:50:27,628] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:50:29,560] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:50:32,631] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5321
[2021-07-25 13:50:47,865] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 13:50:50,020] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 13:50:50,933] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 13:59:58,887] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:00:01,046] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:05:05,602] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:05:07,755] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:06:14,705] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:06:16,770] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:06:31,404] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:06:33,685] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:06:49,903] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:06:52,069] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:07:59,458] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:08:01,733] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:08:29,997] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:08:32,331] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:08:37,785] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 37, in index
    A = Oblist.objects.filter(Status='有意向').aggregrate(Count('Owner'))
AttributeError: 'QuerySet' object has no attribute 'aggregrate'
[2021-07-25 14:08:37,786] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69086
[2021-07-25 14:08:53,757] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:08:55,798] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:08:57,057] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:12:00,358] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:12:02,514] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:12:04,036] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:14:16,270] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:14:18,371] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:14:24,650] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1930, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1623, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1537, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword '__' into field. Choices are: Campaign, Memo, Name, Owner, Phone1, Phone2, Status, id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 37, in index
    A = Oblist.objects.filter(Status='有意向').values(Status).annotate(Count('Owner'))
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 840, in values
    clone = self._values(*fields, **expressions)
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 835, in _values
    clone.query.set_values(fields)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 2246, in set_values
    self.add_fields(field_names, True)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1957, in add_fields
    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword <enum 'Status'> into field. Choices are: Campaign, Memo, Name, Owner, Phone1, Phone2, Status, id
[2021-07-25 14:14:24,654] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 104592
[2021-07-25 14:14:41,603] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:14:43,643] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:14:44,559] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:15:18,684] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:15:21,123] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:15:23,201] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:15:39,564] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:15:41,605] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:15:42,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:16:27,150] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:16:29,267] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:16:31,176] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 38, in index
    print (A.Owner)
AttributeError: 'QuerySet' object has no attribute 'Owner'
[2021-07-25 14:16:31,178] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69327
[2021-07-25 14:16:44,934] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:16:47,026] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:16:55,459] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 38, in index
    print (A['Owner'])
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 290, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2021-07-25 14:16:55,462] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 73385
[2021-07-25 14:17:06,851] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:17:08,962] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:17:12,436] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:20:07,345] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:20:09,375] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:20:10,786] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 41, in index
    i.append(a.Status__count)
AttributeError: 'dict' object has no attribute 'Status__count'
[2021-07-25 14:20:10,788] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69494
[2021-07-25 14:20:34,801] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:20:37,070] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:20:40,521] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5157
[2021-07-25 14:21:07,369] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:21:09,581] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:21:11,577] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5158
[2021-07-25 14:22:25,953] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:22:28,371] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:22:31,937] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 53, in index
    .add_yaxis("未联系", i)
NameError: name 'i' is not defined
[2021-07-25 14:22:31,939] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69811
[2021-07-25 14:23:02,858] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:23:04,993] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:23:05,858] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5138
[2021-07-25 14:26:21,173] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:26:23,219] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:26:25,385] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5138
[2021-07-25 14:26:49,076] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:26:51,117] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:26:52,911] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5138
[2021-07-25 14:27:33,866] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:27:36,078] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:27:36,963] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5214
[2021-07-25 14:31:02,670] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:31:05,012] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:44:35,520] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:44:38,011] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:44:43,961] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 37, in index
    for x in OWNERS.value:
  File "D:\Python39\lib\enum.py", line 405, in __getattr__
    raise AttributeError(name) from None
AttributeError: value
[2021-07-25 14:44:43,964] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 72290
[2021-07-25 14:45:00,085] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:45:02,271] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:45:05,415] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5232
[2021-07-25 14:46:58,133] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:47:00,311] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:47:05,148] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5232
[2021-07-25 14:52:48,225] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:52:50,648] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:53:22,222] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:53:24,833] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:53:38,282] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 14:56:21,163] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:56:23,483] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:56:24,859] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 53, in index
    return HttpResponse(c.render_embed())
AttributeError: 'str' object has no attribute 'render_embed'
[2021-07-25 14:56:24,862] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69777
[2021-07-25 14:57:34,074] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:57:36,448] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:57:50,721] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:57:52,974] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:58:03,795] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 4441
[2021-07-25 14:58:57,358] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:58:59,422] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:59:00,504] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 48, in index
    x = x.add_xaxis("有意向",a1)
TypeError: add_xaxis() takes 2 positional arguments but 3 were given
[2021-07-25 14:59:00,506] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 70030
[2021-07-25 14:59:13,929] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 14:59:16,124] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 14:59:17,053] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 5232
[2021-07-25 15:09:16,001] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:09:18,030] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:09:20,404] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1930, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1623, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1537, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'Status_Count' into field. Choices are: Campaign, Memo, Name, Owner, Phone1, Phone2, Status, id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 43, in index
    y1.append(A.values('Status_Count'))
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 840, in values
    clone = self._values(*fields, **expressions)
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 835, in _values
    clone.query.set_values(fields)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 2246, in set_values
    self.add_fields(field_names, True)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1957, in add_fields
    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'Status_Count' into field. Choices are: Campaign, Memo, Name, Owner, Phone1, Phone2, Status, id
[2021-07-25 15:09:20,407] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 105360
[2021-07-25 15:10:03,692] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:10:05,724] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:10:06,753] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 43, in index
    y1.append(A['Status_Count'])
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 290, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2021-07-25 15:10:06,755] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 73534
[2021-07-25 15:10:21,249] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:10:23,241] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:10:27,351] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 43, in index
    y1.append(A.value['Status_Count'])
AttributeError: 'QuerySet' object has no attribute 'value'
[2021-07-25 15:10:27,352] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69755
[2021-07-25 15:10:35,395] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:10:37,385] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:10:39,581] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 43, in index
    y1.append(A.values['Status_Count'])
TypeError: 'method' object is not subscriptable
[2021-07-25 15:10:39,583] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69663
[2021-07-25 15:11:11,628] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:11:13,707] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:11:14,923] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 48, in index
    return HttpResponse(c.render_embed())
AttributeError: 'str' object has no attribute 'render_embed'
[2021-07-25 15:11:14,935] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69223
[2021-07-25 15:11:44,653] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:11:46,778] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:11:50,274] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 48, in index
    return HttpResponse(c.render_embed())
AttributeError: 'str' object has no attribute 'render_embed'
[2021-07-25 15:11:50,276] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 69035
[2021-07-25 15:12:07,274] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:12:09,362] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:12:10,449] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:12:52,825] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:12:55,118] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:12:57,308] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:13:03,535] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:13:34,934] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:13:37,006] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:13:38,215] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:15:02,633] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:15:04,967] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:15:06,419] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:15:09,239] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:16:01,578] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:16:03,726] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:16:04,675] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 46, in index
    y1=y1.append(A.count())
AttributeError: 'NoneType' object has no attribute 'append'
[2021-07-25 15:16:04,677] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/ HTTP/1.1" 500 70518
[2021-07-25 15:16:23,111] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:16:25,282] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:16:26,390] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:16:54,276] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:16:56,339] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:16:57,550] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 3622
[2021-07-25 15:17:35,075] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-25 15:17:37,227] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-25 15:17:42,497] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 8183
