[2021-10-05 20:21:19,688] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:21:22,731] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:21:22,794] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.css?_=2.1 HTTP/1.1" 200 3861
[2021-10-05 20:21:22,795] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/css/all.min.css HTTP/1.1" 200 55111
[2021-10-05 20:21:22,804] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/index.css HTTP/1.1" 200 232478
[2021-10-05 20:21:22,806] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css?_=3.2 HTTP/1.1" 200 6608
[2021-10-05 20:21:22,825] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2021.5.21 HTTP/1.1" 200 6292
[2021-10-05 20:21:22,825] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2021.5.21 HTTP/1.1" 200 1186
[2021-10-05 20:21:22,827] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/vue.min.js?_=2021.5.21 HTTP/1.1" 200 93675
[2021-10-05 20:21:22,827] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.5.21 HTTP/1.1" 200 811
[2021-10-05 20:21:22,828] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.5.21 HTTP/1.1" 200 1254
[2021-10-05 20:21:22,839] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2021.5.21 HTTP/1.1" 200 524
[2021-10-05 20:21:22,840] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2021.5.21 HTTP/1.1" 200 4274
[2021-10-05 20:21:22,843] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2021.5.21 HTTP/1.1" 200 6329
[2021-10-05 20:21:22,844] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2021.5.21 HTTP/1.1" 200 1189
[2021-10-05 20:21:22,847] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2021.5.21 HTTP/1.1" 200 20820
[2021-10-05 20:21:22,899] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/Miracle-Logo-1.png HTTP/1.1" 200 24169
[2021-10-05 20:21:22,907] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/index.js?_=2021.5.21 HTTP/1.1" 200 567853
[2021-10-05 20:21:23,195] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/fonts/element-icons.woff HTTP/1.1" 200 28200
[2021-10-05 20:21:23,195] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 74256
[2021-10-05 20:21:23,200] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13552
[2021-10-05 20:21:23,443] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-10-05 20:21:23,444] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 8686
[2021-10-05 20:21:27,204] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:21:27,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css?_=3.2 HTTP/1.1" 200 6608
[2021-10-05 20:21:27,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.css?_=2.1 HTTP/1.1" 200 3861
[2021-10-05 20:21:27,238] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/css/all.min.css HTTP/1.1" 200 55111
[2021-10-05 20:21:27,241] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/index.css HTTP/1.1" 200 232478
[2021-10-05 20:21:27,260] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js?_=2021.5.21 HTTP/1.1" 200 1186
[2021-10-05 20:21:27,261] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js?_=2021.5.21 HTTP/1.1" 200 6292
[2021-10-05 20:21:27,262] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2021.5.21 HTTP/1.1" 200 811
[2021-10-05 20:21:27,266] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js?_=2021.5.21 HTTP/1.1" 200 1254
[2021-10-05 20:21:27,270] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js?_=2021.5.21 HTTP/1.1" 200 524
[2021-10-05 20:21:27,272] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js?_=2021.5.21 HTTP/1.1" 200 6329
[2021-10-05 20:21:27,272] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/theme.js?_=2021.5.21 HTTP/1.1" 200 4274
[2021-10-05 20:21:27,272] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/vue.min.js?_=2021.5.21 HTTP/1.1" 200 93675
[2021-10-05 20:21:27,272] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/menu.js?_=2021.5.21 HTTP/1.1" 200 1189
[2021-10-05 20:21:27,277] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/images/Miracle-Logo-1.png HTTP/1.1" 200 24169
[2021-10-05 20:21:27,278] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/index.js?_=2021.5.21 HTTP/1.1" 200 20820
[2021-10-05 20:21:27,284] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/index.js?_=2021.5.21 HTTP/1.1" 200 567853
[2021-10-05 20:21:27,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/elementui/theme-chalk/fonts/element-icons.woff HTTP/1.1" 200 28200
[2021-10-05 20:21:27,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-regular-400.woff2 HTTP/1.1" 200 13552
[2021-10-05 20:21:27,491] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/fontawesome-free-5.8.1-web/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 74256
[2021-10-05 20:21:27,714] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-10-05 20:21:27,714] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 8686
[2021-10-05 20:21:33,328] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/park/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Park has no field named 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\Python39\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\Python39\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "D:\Python39\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 278, in lookup_field
    value = attr()
  File "E:\djangoProject\Park\models.py", line 31, in pass_audit_str
    parameter_str = 'id={}&status={}'.format(str(self.id), str(self.audit))
AttributeError: 'Park' object has no attribute 'audit'
[2021-10-05 20:21:33,347] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/park/ HTTP/1.1" 500 484729
[2021-10-05 20:22:14,783] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 20:22:17,495] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:22:22,566] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:22:23,207] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49919
[2021-10-05 20:22:23,224] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2.1.2 HTTP/1.1" 200 811
[2021-10-05 20:22:23,225] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/language.js?_=2.1.2 HTTP/1.1" 200 189
[2021-10-05 20:22:23,228] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js HTTP/1.1" 200 1254
[2021-10-05 20:22:23,230] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 200 6874
[2021-10-05 20:22:23,231] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css?_=2.7 HTTP/1.1" 200 19513
[2021-10-05 20:22:23,233] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css?_=20180905 HTTP/1.1" 200 18545
[2021-10-05 20:22:23,234] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js HTTP/1.1" 200 524
[2021-10-05 20:22:23,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2021-10-05 20:22:23,237] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2021-10-05 20:22:23,239] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/base.css?_=2.7 HTTP/1.1" 200 3323
[2021-10-05 20:22:23,241] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[2021-10-05 20:22:23,241] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/simpleui.css HTTP/1.1" 200 4270
[2021-10-05 20:22:23,243] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[2021-10-05 20:22:23,244] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 7664
[2021-10-05 20:22:23,246] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[2021-10-05 20:22:23,247] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[2021-10-05 20:22:23,250] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js HTTP/1.1" 200 6292
[2021-10-05 20:22:23,252] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js HTTP/1.1" 200 1186
[2021-10-05 20:22:23,253] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89476
[2021-10-05 20:22:23,254] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/axios.min.js HTTP/1.1" 200 14237
[2021-10-05 20:22:23,256] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2021-10-05 20:22:23,259] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[2021-10-05 20:22:23,418] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:22:23,511] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2021-10-05 20:22:23,555] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2021-10-05 20:24:47,344] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:24:50,079] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:25:11,787] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 20:25:14,515] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:25:16,845] [log.py:224] [log:log_response] [WARNING]- Not Found: /pass_audit/
[2021-10-05 20:25:16,847] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /pass_audit/?id=5&status=test HTTP/1.1" 404 8707
[2021-10-05 20:25:20,758] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:25:23,968] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:25:24,767] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:25:24,927] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:25:28,052] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'XY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 104, in hello
    "location":req.GET['XY'],
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'XY'
[2021-10-05 20:25:28,054] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 85218
[2021-10-05 20:27:24,659] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:27:27,373] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:27:31,905] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:27:32,086] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:27:34,794] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 106, in hello
    "location":XY,
UnboundLocalError: local variable 'XY' referenced before assignment
[2021-10-05 20:27:34,796] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 54495)

[2021-10-05 20:27:34,891] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 106, in hello
    "location":XY,
UnboundLocalError: local variable 'XY' referenced before assignment
[2021-10-05 20:27:34,894] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77197
[2021-10-05 20:28:01,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 20:28:01,703] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:28:05,527] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:28:05,692] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:28:34,017] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:28:36,751] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:28:38,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:28:39,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:28:39,404] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:28:42,650] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 106, in hello
    "location":XY,
UnboundLocalError: local variable 'XY' referenced before assignment
[2021-10-05 20:28:42,652] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77296
[2021-10-05 20:29:01,567] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:29:04,330] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:29:07,529] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:29:08,139] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:29:08,286] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:29:13,364] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 112, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:29:13,367] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77770
[2021-10-05 20:30:11,982] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:30:14,779] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:30:15,823] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:30:16,443] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:30:16,607] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:30:19,435] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 113, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:30:19,437] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77836
[2021-10-05 20:31:25,581] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:31:28,308] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:31:30,017] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 20:31:30,171] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:31:31,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:31:32,024] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:31:33,979] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 112, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:31:33,980] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77737
[2021-10-05 20:32:01,455] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:32:04,225] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:32:06,343] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:32:06,736] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:32:08,599] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 112, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:32:08,600] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 55586)

[2021-10-05 20:32:08,994] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 112, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:32:08,995] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77836
[2021-10-05 20:33:18,902] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:33:21,621] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:33:23,681] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:33:23,849] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:33:25,260] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: hello() missing 2 required positional arguments: 'Status' and 'req'
[2021-10-05 20:33:25,260] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 65937
[2021-10-05 20:34:43,114] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:34:45,813] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:35:11,201] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:35:14,068] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:35:51,565] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:35:54,238] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:36:05,401] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:36:07,089] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:36:12,276] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:36:12,297] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/base.css?_=2.7 HTTP/1.1" 200 3323
[2021-10-05 20:36:12,301] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css?_=2.7 HTTP/1.1" 200 19513
[2021-10-05 20:36:12,304] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/en-us.js?_=2.1.2 HTTP/1.1" 200 811
[2021-10-05 20:36:12,305] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/simpleui.css HTTP/1.1" 200 4270
[2021-10-05 20:36:12,305] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 200 6874
[2021-10-05 20:36:12,305] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/language.js?_=2.1.2 HTTP/1.1" 200 189
[2021-10-05 20:36:12,310] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css?_=20180905 HTTP/1.1" 200 18545
[2021-10-05 20:36:12,311] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/locale/zh-hans.js HTTP/1.1" 200 1254
[2021-10-05 20:36:12,316] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2021-10-05 20:36:12,316] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/cookie.js HTTP/1.1" 200 524
[2021-10-05 20:36:12,319] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[2021-10-05 20:36:12,319] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[2021-10-05 20:36:12,321] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[2021-10-05 20:36:12,322] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 7664
[2021-10-05 20:36:12,325] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[2021-10-05 20:36:12,326] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[2021-10-05 20:36:12,332] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/dicts.js HTTP/1.1" 200 6292
[2021-10-05 20:36:12,332] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/automatic/segment.js HTTP/1.1" 200 1186
[2021-10-05 20:36:12,333] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89476
[2021-10-05 20:36:12,335] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[2021-10-05 20:36:12,335] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/axios.min.js HTTP/1.1" 200 14237
[2021-10-05 20:36:12,335] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2021-10-05 20:36:12,482] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:36:12,597] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2021-10-05 20:36:12,656] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2021-10-05 20:36:14,810] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: hello() missing 1 required positional argument: 'Status'
[2021-10-05 20:36:14,810] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 61575)

[2021-10-05 20:36:14,954] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: hello() missing 1 required positional argument: 'Status'
[2021-10-05 20:36:14,955] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 65861
[2021-10-05 20:36:39,206] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:36:49,455] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:36:50,425] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:36:52,389] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:36:53,298] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:36:57,108] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:36:57,632] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:37:00,121] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:37:00,701] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:37:01,445] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 20:37:02,042] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:37:02,216] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:37:04,465] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: hello() missing 1 required positional argument: 'status'
[2021-10-05 20:37:04,466] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 65861
[2021-10-05 20:39:58,451] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:39:58,458] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:40:01,423] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:40:01,439] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:40:10,068] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:40:10,230] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:40:12,057] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 103, in hello
    "location":req.POST['status'],
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
[2021-10-05 20:40:12,058] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77535
[2021-10-05 20:41:13,863] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:41:14,322] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:41:16,854] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:41:17,286] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:41:19,472] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:41:19,872] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:41:21,488] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 96, in hello
    print (req.POST['status'])
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
[2021-10-05 20:41:21,491] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 77641
[2021-10-05 20:41:56,367] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:41:57,411] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:41:59,171] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:42:00,221] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:42:11,925] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:42:12,169] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:42:14,783] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:42:15,022] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:42:16,969] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:42:17,123] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:42:19,037] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 96, in hello
    print ('Status的值是：',req.POST['status'])
  File "D:\Python39\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'status'
[2021-10-05 20:42:19,040] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 77736
[2021-10-05 20:44:48,902] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:44:49,783] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:44:51,814] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:44:52,642] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:44:55,816] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:44:56,211] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:44:58,739] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:44:58,741] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 70164
[2021-10-05 20:45:22,537] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:45:22,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:46:42,715] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:46:42,941] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:46:45,610] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:46:45,810] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:46:47,538] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:46:47,540] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 70065
[2021-10-05 20:48:19,012] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:48:19,917] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:48:21,903] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:48:22,854] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:48:25,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:48:25,878] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:48:27,723] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:48:27,725] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 70065
[2021-10-05 20:49:21,563] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:49:22,144] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:49:24,350] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:49:25,061] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:49:26,247] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:49:29,023] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:49:30,090] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 20:49:30,264] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:49:30,891] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:49:31,064] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:49:33,101] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:49:33,102] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 70131
[2021-10-05 20:49:57,008] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:49:57,167] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:50:05,732] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:50:05,733] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 70164
[2021-10-05 20:50:19,893] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:50:20,175] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:50:22,902] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:50:23,232] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:50:24,763] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:50:24,921] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:50:26,967] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:50:26,970] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 70164
[2021-10-05 20:51:57,795] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:51:58,372] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:52:00,612] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:52:01,237] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:52:04,093] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:52:04,250] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:52:07,154] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 109, in hello
    context['res3']=json.loads(res3.text)['result']
KeyError: 'result'
[2021-10-05 20:52:07,155] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 70131
[2021-10-05 20:52:39,598] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:52:39,782] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:52:42,578] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:52:42,721] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:52:44,342] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:52:44,512] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:52:46,203] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 112, in hello
    return render("a_hello.html", context)
  File "D:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python39\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "D:\Python39\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "D:\Python39\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "D:\Python39\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\Python39\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
[2021-10-05 20:52:46,209] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 138758
[2021-10-05 20:53:38,006] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:53:38,939] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:53:40,809] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:53:41,740] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:53:48,573] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:53:51,384] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:53:52,628] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:53:52,789] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:53:54,976] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 115, in hello
    return render("a_hello.html", context)
  File "D:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python39\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "D:\Python39\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "D:\Python39\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "D:\Python39\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\Python39\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
[2021-10-05 20:53:54,981] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 138955
[2021-10-05 20:55:35,051] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:55:35,215] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:56:25,321] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:56:28,197] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:56:30,378] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "D:\Python39\lib\site-packages\django\middleware\common.py", line 107, in process_response
    if response.status_code == 404 and self.should_redirect_with_slash(request):
AttributeError: 'str' object has no attribute 'status_code'
[2021-10-05 20:56:30,379] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 71456
[2021-10-05 20:57:29,597] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:57:32,409] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:57:34,343] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:57:34,513] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:57:36,046] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 672
[2021-10-05 20:57:47,777] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:57:47,939] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:57:50,395] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 672
[2021-10-05 20:58:32,549] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:58:35,466] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:58:36,894] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:58:37,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:58:38,912] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 118, in hello
    return HttpResponse(res3.text['result'])
TypeError: string indices must be integers
[2021-10-05 20:58:38,914] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 500 72246
[2021-10-05 20:59:03,816] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 20:59:06,651] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 20:59:08,128] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 20:59:08,293] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 20:59:09,426] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=4&status=32.50686601763335,80.11277692192645 HTTP/1.1" 200 95
[2021-10-05 21:00:59,584] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:01:02,373] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:01:06,559] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:01:06,711] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:01:18,528] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:01:21,360] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:01:31,632] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:01:31,807] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:01:33,512] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 119, in hello
    return HttpResponse(add.addressComponent.city)
AttributeError: 'dict' object has no attribute 'addressComponent'
[2021-10-05 21:01:33,514] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 500 74164
[2021-10-05 21:02:33,411] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:02:36,129] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:02:42,491] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:02:42,658] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:02:44,458] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 137
[2021-10-05 21:03:05,027] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:03:07,813] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:03:10,195] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:03:10,360] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:03:12,134] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 9
[2021-10-05 21:04:18,418] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:04:21,143] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:04:24,667] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:04:27,488] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:04:29,890] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:04:30,055] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:04:31,784] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 39
[2021-10-05 21:04:41,309] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:04:41,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:04:43,190] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=2&status=31.217354656742838,121.32414072682006 HTTP/1.1" 200 39
[2021-10-05 21:05:24,376] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:05:27,540] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:05:53,172] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:05:56,182] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:06:08,980] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:06:10,430] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 21:06:13,966] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:06:14,135] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:06:16,145] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/?id=3&status=31.20925787688284,121.3215650154313 HTTP/1.1" 200 39
[2021-10-05 21:06:28,947] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:06:29,106] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:08:54,707] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:08:54,990] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:08:57,844] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:08:58,205] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:09:04,584] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2021-10-05 21:09:04,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/favicon.ico HTTP/1.1" 200 4088
[2021-10-05 21:09:05,172] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 302 0
[2021-10-05 21:09:05,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /login/?next=/favicon.ico HTTP/1.1" 200 4088
[2021-10-05 21:09:05,968] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello HTTP/1.1" 301 0
[2021-10-05 21:09:07,180] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Miracle/Hello/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 120, in hello
    return render("a_hello.html", context)
  File "D:\Python39\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python39\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python39\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python39\lib\site-packages\django\template\loaders\base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "D:\Python39\lib\site-packages\django\template\loaders\filesystem.py", line 36, in get_template_sources
    name = safe_join(template_dir, template_name)
  File "D:\Python39\lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
  File "D:\Python39\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\Python39\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
[2021-10-05 21:09:07,185] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Miracle/Hello/ HTTP/1.1" 500 183243
[2021-10-05 21:09:21,368] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:09:21,423] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-10-05 21:09:24,430] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:09:24,448] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:09:25,422] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/ HTTP/1.1" 200 4285
[2021-10-05 21:09:25,486] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/popper/popper.js HTTP/1.1" 200 69253
[2021-10-05 21:09:25,486] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/jquery/jquery-3.6.0.min.js HTTP/1.1" 200 89503
[2021-10-05 21:09:25,510] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/js/bootstrap.js HTTP/1.1" 200 148340
[2021-10-05 21:09:25,515] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/css/bootstrap.css HTTP/1.1" 200 209709
[2021-10-05 21:10:03,604] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49934
[2021-10-05 21:10:03,772] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:11:14,703] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:11:14,722] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:11:15,421] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:11:17,718] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:11:17,719] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:11:18,323] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:15:56,580] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:15:56,693] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:15:56,741] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:15:59,678] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:15:59,764] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:15:59,831] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:34,635] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:35,288] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:35,290] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:37,521] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:38,302] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:38,302] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:48,139] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:48,582] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:48,636] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:16:51,057] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:51,539] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:51,572] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:16:56,825] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 21:16:57,380] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/park/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python39\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Python39\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Python39\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python39\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Park_park.Address' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python39\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "D:\Python39\lib\site-packages\import_export\admin.py", line 341, in changelist_view
    return super().changelist_view(request, extra_context)
  File "D:\Python39\lib\site-packages\import_export\admin.py", line 504, in changelist_view
    return super().changelist_view(request, extra_context)
  File "D:\Python39\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python39\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python39\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python39\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\Python39\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Python39\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Python39\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Python39\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Python39\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'Park_park.Address' in 'field list'")
[2021-10-05 21:16:57,396] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/park/ HTTP/1.1" 500 231679
[2021-10-05 21:17:01,773] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 21:17:01,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:17:24,879] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/park/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Park has no field named 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\Python39\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\Python39\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "D:\Python39\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 278, in lookup_field
    value = attr()
  File "E:\djangoProject\Park\models.py", line 31, in pass_audit_str
    parameter_str = 'id={}&status={}'.format(str(self.id), str(self.XY))
AttributeError: 'Park' object has no attribute 'XY'
[2021-10-05 21:17:24,900] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/park/ HTTP/1.1" 500 484807
[2021-10-05 21:17:30,799] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/park/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Park has no field named 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\Python39\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\Python39\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "D:\Python39\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 278, in lookup_field
    value = attr()
  File "E:\djangoProject\Park\models.py", line 31, in pass_audit_str
    parameter_str = 'id={}&status={}'.format(str(self.id), str(self.XY))
AttributeError: 'Park' object has no attribute 'XY'
[2021-10-05 21:17:30,816] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/park/ HTTP/1.1" 500 484807
[2021-10-05 21:17:57,077] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:17:58,826] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25722
[2021-10-05 21:18:12,195] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/park/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "D:\Python39\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Park has no field named 'pass_audit_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "D:\Python39\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\Python39\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "D:\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "D:\Python39\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "D:\Python39\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "D:\Python39\lib\site-packages\django\contrib\admin\utils.py", line 278, in lookup_field
    value = attr()
  File "E:\djangoProject\Park\models.py", line 31, in pass_audit_str
    parameter_str = 'id={}&status={}'.format(str(self.id), str(self.XY))
AttributeError: 'Park' object has no attribute 'XY'
[2021-10-05 21:18:12,201] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/park/ HTTP/1.1" 500 484807
[2021-10-05 21:18:29,551] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:18:29,551] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:18:30,086] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:18:32,595] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:18:32,598] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:18:33,050] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:18:37,155] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 21:18:37,323] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:18:42,020] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 48852
[2021-10-05 21:18:42,195] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:18:46,554] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/5/change/ HTTP/1.1" 200 21165
[2021-10-05 21:18:46,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
[2021-10-05 21:18:46,593] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/autocomplete.css HTTP/1.1" 200 9114
[2021-10-05 21:18:46,594] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/vendor/select2/select2.css HTTP/1.1" 200 17358
[2021-10-05 21:18:46,596] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/autocomplete.js HTTP/1.1" 200 1320
[2021-10-05 21:18:46,599] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/select2/select2.full.js HTTP/1.1" 200 173566
[2021-10-05 21:18:46,614] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[2021-10-05 21:18:46,618] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2021-10-05 21:18:46,628] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[2021-10-05 21:18:46,632] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2021-10-05 21:18:46,638] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2021-10-05 21:18:46,778] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:18:49,967] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 48852
[2021-10-05 21:18:50,150] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:18:56,226] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/5/change/ HTTP/1.1" 200 21165
[2021-10-05 21:18:56,399] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:20:50,792] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 48852
[2021-10-05 21:20:50,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:22:09,512] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/5/change/ HTTP/1.1" 200 21165
[2021-10-05 21:22:09,540] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
[2021-10-05 21:22:09,542] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/autocomplete.css HTTP/1.1" 200 9114
[2021-10-05 21:22:09,544] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/vendor/select2/select2.css HTTP/1.1" 200 17358
[2021-10-05 21:22:09,545] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/autocomplete.js HTTP/1.1" 200 1320
[2021-10-05 21:22:09,548] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/select2/select2.full.js HTTP/1.1" 200 173566
[2021-10-05 21:22:09,570] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[2021-10-05 21:22:09,702] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:22:09,707] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[2021-10-05 21:22:09,714] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[2021-10-05 21:22:09,719] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2021-10-05 21:22:09,724] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2021-10-05 21:22:33,040] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/5/change/ HTTP/1.1" 302 0
[2021-10-05 21:22:33,432] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49277
[2021-10-05 21:22:33,836] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:22:53,832] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:22:53,897] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:22:54,937] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:22:56,957] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:22:56,966] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:22:57,937] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:23:58,149] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:23:58,163] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:23:58,693] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:24:01,155] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:24:01,155] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:24:01,608] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:25:49,417] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello HTTP/1.1" 301 0
[2021-10-05 21:25:49,657] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/Hello/ HTTP/1.1" 200 4285
[2021-10-05 21:25:49,687] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/jquery/jquery-3.6.0.min.js HTTP/1.1" 200 89503
[2021-10-05 21:25:49,689] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/popper/popper.js HTTP/1.1" 200 69253
[2021-10-05 21:25:49,691] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/css/bootstrap.css HTTP/1.1" 200 209709
[2021-10-05 21:25:49,691] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/js/bootstrap.js HTTP/1.1" 200 148340
[2021-10-05 21:30:22,773] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-10-05 21:30:22,773] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-10-05 21:30:22,970] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-10-05 21:30:25,858] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:30:25,860] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:30:26,011] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:31:19,996] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25696
[2021-10-05 21:31:38,016] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:31:38,094] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:31:38,251] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:31:41,066] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:31:41,130] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:31:41,209] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:32:27,380] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:32:27,701] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-10-05 21:32:27,737] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:32:30,341] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:32:30,739] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:32:30,754] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:32:33,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49127
[2021-10-05 21:32:33,575] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:32:43,120] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 23, in GetStreet
    res23 = str(res22['result']['location']['lat'])+','+str(res22['result']['location']['lng'])
KeyError: 'result'
[2021-10-05 21:32:43,121] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=5&status=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E6%B7%AE%E8%99%B9%E8%B7%AF958%E5%BC%841%E5%8F%B7 HTTP/1.1" 500 71214
[2021-10-05 21:33:19,933] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:33:19,951] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:33:20,103] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:33:23,019] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:33:23,021] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:33:23,185] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:33:27,258] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 21:33:27,422] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:33:28,427] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49132
[2021-10-05 21:33:28,585] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:33:32,810] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=5&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E6%B7%AE%E8%99%B9%E8%B7%AF958%E5%BC%841%E5%8F%B7 HTTP/1.1" 200 39
[2021-10-05 21:33:43,844] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49132
[2021-10-05 21:33:44,009] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:34:00,958] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/4/change/ HTTP/1.1" 200 21162
[2021-10-05 21:34:01,131] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:34:25,097] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:34:25,548] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:34:25,580] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:34:28,109] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:34:28,620] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:34:28,640] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:35:10,931] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:35:13,888] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:35:20,506] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:35:23,227] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:35:27,749] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49132
[2021-10-05 21:35:27,910] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:35:31,846] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 62217)

[2021-10-05 21:35:31,918] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/4/change/ HTTP/1.1" 200 21162
[2021-10-05 21:35:32,092] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:36:08,529] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:36:10,049] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25696
[2021-10-05 21:36:13,004] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49132
[2021-10-05 21:36:13,173] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:36:15,906] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/4/change/ HTTP/1.1" 200 21162
[2021-10-05 21:36:16,103] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:36:44,952] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/4/change/ HTTP/1.1" 302 0
[2021-10-05 21:36:45,325] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49541
[2021-10-05 21:36:45,525] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:36:48,586] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 20, in GetStreet
    print (res2)
OSError: [Errno 22] Invalid argument
[2021-10-05 21:36:48,588] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 500 70861
[2021-10-05 21:37:12,205] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25681
[2021-10-05 21:37:12,693] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:37:13,744] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25681
[2021-10-05 21:37:17,930] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49398
[2021-10-05 21:37:18,108] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:37:20,462] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 20, in GetStreet
    print (res2)
OSError: [Errno 22] Invalid argument
[2021-10-05 21:37:20,464] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 500 70863
[2021-10-05 21:37:44,838] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:37:45,569] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:37:47,742] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:37:48,442] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:37:52,554] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49398
[2021-10-05 21:37:52,735] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:37:54,579] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 200 48
[2021-10-05 21:41:18,145] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:41:18,681] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:41:21,020] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:41:21,555] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:41:27,412] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 21:41:27,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:41:28,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49398
[2021-10-05 21:41:28,652] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:41:33,344] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 53, in GetStreet
    qs.objects.update(Street=add1)
  File "D:\Python39\lib\site-packages\django\db\models\manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via Park instances
[2021-10-05 21:41:33,347] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 500 80470
[2021-10-05 21:42:09,816] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:42:10,094] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:42:12,682] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:42:12,948] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:42:19,024] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49398
[2021-10-05 21:42:19,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:42:21,522] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 52, in GetStreet
    Park.objects.get(id=req.GET['id']).update(Street=add1)
AttributeError: 'Park' object has no attribute 'update'
[2021-10-05 21:42:21,523] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 500 76386
[2021-10-05 21:43:55,528] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:43:55,897] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:43:58,401] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:43:58,759] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:44:04,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49398
[2021-10-05 21:44:04,851] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:44:07,770] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 200 48
[2021-10-05 21:44:12,115] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 49668
[2021-10-05 21:44:12,287] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:46:05,144] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:46:05,147] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:46:05,243] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:46:05,395] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:46:08,310] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:46:08,312] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:46:08,326] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:46:08,433] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:47:58,726] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:47:58,770] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:47:59,460] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:47:59,882] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:48:01,936] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:01,954] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:02,602] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:02,889] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:25,294] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:48:25,683] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:48:25,700] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:48:25,768] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:48:28,369] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:28,841] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:28,843] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:28,896] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:48:57,479] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:48:57,511] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:48:58,073] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:48:58,192] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 21:49:00,708] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:49:00,739] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:49:01,349] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:49:01,444] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:49:21,304] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25681
[2021-10-05 21:49:22,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51296
[2021-10-05 21:49:22,349] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:50:33,896] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:33,904] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:33,957] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:34,430] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:37,203] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:50:37,207] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:50:37,640] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:50:38,834] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25681
[2021-10-05 21:50:39,397] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51296
[2021-10-05 21:50:39,544] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:50:44,283] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /Park/GetStreet/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Park\views.py", line 54, in GetStreet
    qs.City=add['addressComponent']['City']
KeyError: 'City'
[2021-10-05 21:50:44,284] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /Park/GetStreet/?id=5&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E6%B7%AE%E8%99%B9%E8%B7%AF958%E5%BC%841%E5%8F%B7 HTTP/1.1" 500 76886
[2021-10-05 21:50:59,932] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:59,955] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:50:59,985] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:51:00,196] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 21:51:03,377] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:51:03,380] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:51:03,380] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:51:03,461] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:51:04,784] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51296
[2021-10-05 21:51:04,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:51:06,729] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=5&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E6%B7%AE%E8%99%B9%E8%B7%AF958%E5%BC%841%E5%8F%B7 HTTP/1.1" 200 39
[2021-10-05 21:51:10,416] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51763
[2021-10-05 21:51:10,565] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:51:18,884] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 200 48
[2021-10-05 21:51:23,454] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51824
[2021-10-05 21:51:23,653] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:52:13,918] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/3/change/ HTTP/1.1" 200 22125
[2021-10-05 21:52:14,106] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:52:43,431] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/3/change/ HTTP/1.1" 200 22596
[2021-10-05 21:52:43,618] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 21:56:09,118] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:09,269] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:09,543] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:09,587] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:12,262] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:12,457] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:12,729] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:12,734] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:51,626] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:52,404] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:52,472] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:52,657] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 21:56:54,998] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:55,673] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:55,715] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 21:56:55,860] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:00:39,983] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:00:40,182] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:00:40,811] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:00:41,019] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:00:43,173] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:00:43,377] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:00:44,021] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:00:44,199] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:01:17,595] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:01:17,918] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:01:18,029] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:01:18,042] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:01:20,846] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:01:21,236] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:01:21,385] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:01:21,386] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:01:29,881] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25681
[2021-10-05 22:01:30,517] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 51824
[2021-10-05 22:01:30,928] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:01:33,512] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/3/change/ HTTP/1.1" 200 37038
[2021-10-05 22:01:33,700] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:01:44,874] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=Park&model_name=park&field_name=PM HTTP/1.1" 200 87
[2021-10-05 22:02:30,657] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/3/change/ HTTP/1.1" 302 0
[2021-10-05 22:02:31,053] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52221
[2021-10-05 22:02:31,471] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:02:36,104] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=3&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E7%94%B3%E8%99%B9%E8%B7%AF663%E5%8F%B7 HTTP/1.1" 200 39
[2021-10-05 22:02:40,040] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52255
[2021-10-05 22:02:40,205] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:03:03,999] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:03:04,124] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:03:04,245] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:03:04,380] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:03:07,093] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:03:07,235] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:03:07,334] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:03:07,472] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:03:08,809] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=5&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E6%B7%AE%E8%99%B9%E8%B7%AF958%E5%BC%841%E5%8F%B7 HTTP/1.1" 200 39
[2021-10-05 22:03:13,087] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52264
[2021-10-05 22:03:13,289] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:03:15,879] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=4&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E6%B5%A6%E4%B8%9C%E6%96%B0%E5%8C%BA%E4%B8%9C%E6%96%B9%E8%B7%AF971%E5%8F%B7 HTTP/1.1" 200 48
[2021-10-05 22:03:18,572] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 22:03:18,736] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:03:25,528] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52291
[2021-10-05 22:03:25,696] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:03:29,179] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=3&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E7%94%B3%E8%99%B9%E8%B7%AF663%E5%8F%B7 HTTP/1.1" 200 39
[2021-10-05 22:03:33,745] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52149
[2021-10-05 22:03:33,930] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:04:01,174] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=2 HTTP/1.1" 200 52968
[2021-10-05 22:04:01,293] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 65334)

[2021-10-05 22:04:01,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:04:01,447] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[2021-10-05 22:04:01,484] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2021-10-05 22:04:03,447] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=-2 HTTP/1.1" 200 52985
[2021-10-05 22:04:03,614] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:04:05,650] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/2/change/?_changelist_filters=o%3D-2 HTTP/1.1" 200 37135
[2021-10-05 22:04:05,829] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:04:27,321] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/2/change/?_changelist_filters=o%3D-2 HTTP/1.1" 302 0
[2021-10-05 22:04:27,732] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=-2 HTTP/1.1" 200 53362
[2021-10-05 22:04:27,915] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:04:30,139] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 64587)

[2021-10-05 22:04:30,259] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetStreet/?id=2&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E7%94%B3%E8%B4%B5%E8%B7%AF1799%E5%BC%84 HTTP/1.1" 200 39
[2021-10-05 22:04:40,499] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52406
[2021-10-05 22:04:40,657] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:05:26,147] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:05:26,571] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:05:26,577] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:05:26,648] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\views.py changed, reloading.
[2021-10-05 22:05:29,363] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:05:29,850] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:05:29,850] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:05:29,862] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:05:54,991] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-10-05 22:05:58,192] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:06:35,402] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:06:36,961] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25623
[2021-10-05 22:06:40,044] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25623
[2021-10-05 22:06:40,622] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52396
[2021-10-05 22:06:40,783] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:06:58,083] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?Street=%E6%96%B0%E8%99%B9%E8%A1%97%E9%81%93 HTTP/1.1" 200 50864
[2021-10-05 22:06:58,266] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:07:06,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?Street=%E6%BD%8D%E5%9D%8A%E6%96%B0%E6%9D%91%E8%A1%97%E9%81%93 HTTP/1.1" 200 48139
[2021-10-05 22:07:06,733] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:07:10,126] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?Street=%E6%96%B0%E8%99%B9%E8%A1%97%E9%81%93 HTTP/1.1" 200 50864
[2021-10-05 22:07:10,304] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:07:52,151] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:07:52,159] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:07:52,269] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:07:52,595] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:07:52,837] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:07:55,426] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:07:55,428] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:07:55,531] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:07:55,875] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:07:56,128] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:15,674] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:15,735] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:15,744] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:15,759] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:16,007] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:19,290] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:19,362] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:19,362] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:19,389] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:19,446] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:31,548] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:32,343] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:32,362] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:32,387] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:32,414] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:08:34,737] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:35,806] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:35,824] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:35,835] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:35,855] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:08:45,851] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 22:08:46,024] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:08:55,165] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/? HTTP/1.1" 200 52417
[2021-10-05 22:08:55,352] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:08:59,689] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetTown/?id=1&Address=None HTTP/1.1" 200 42
[2021-10-05 22:09:07,639] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52503
[2021-10-05 22:09:07,785] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:09:10,405] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/1/change/ HTTP/1.1" 200 37106
[2021-10-05 22:09:10,587] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:09:40,025] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/1/change/ HTTP/1.1" 302 0
[2021-10-05 22:09:40,446] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52769
[2021-10-05 22:09:40,627] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:09:42,795] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetTown/?id=1&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%97%B5%E8%A1%8C%E5%8C%BA%E7%94%B3%E9%95%BF%E8%B7%AF1688%E5%BC%84 HTTP/1.1" 200 39
[2021-10-05 22:09:46,698] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parklog/ HTTP/1.1" 200 41655
[2021-10-05 22:09:46,852] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:09:48,063] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52176
[2021-10-05 22:09:48,228] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:09:49,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/street/ HTTP/1.1" 200 38249
[2021-10-05 22:09:49,834] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:10:15,060] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:10:15,569] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:10:15,616] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:10:15,734] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:10:15,793] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:10:18,427] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:19,059] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:19,089] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:19,213] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:19,236] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:40,504] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:10:41,205] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:10:41,308] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:10:41,351] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:10:41,359] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\admin.py changed, reloading.
[2021-10-05 22:10:43,718] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:44,608] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:44,703] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:44,738] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:44,753] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:10:48,143] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25317
[2021-10-05 22:10:48,735] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52176
[2021-10-05 22:10:48,894] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:11:11,969] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:11:12,462] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:11:12,558] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:11:12,585] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:11:12,645] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:11:15,112] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:11:15,748] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:11:15,881] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:11:15,913] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:11:15,956] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:11:18,219] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25341
[2021-10-05 22:11:18,815] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52176
[2021-10-05 22:11:18,964] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:11:21,444] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parklog/ HTTP/1.1" 200 41661
[2021-10-05 22:11:21,460] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 22:11:21,604] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:11:21,754] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:11:27,996] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parklog/add/ HTTP/1.1" 200 19523
[2021-10-05 22:11:28,176] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:11:29,457] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=Park&model_name=parklog&field_name=Park HTTP/1.1" 200 313
[2021-10-05 22:11:54,103] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/parklog/add/ HTTP/1.1" 302 0
[2021-10-05 22:11:54,503] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parklog/ HTTP/1.1" 200 43012
[2021-10-05 22:11:54,689] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:14,076] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /tasks/task/ HTTP/1.1" 200 60146
[2021-10-05 22:12:14,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:16,471] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/miraclenumber/ HTTP/1.1" 200 74628
[2021-10-05 22:12:17,637] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:21,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /CloudNet/card/ HTTP/1.1" 200 65783
[2021-10-05 22:12:21,354] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:23,405] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /CloudNet/ticket/ HTTP/1.1" 200 54031
[2021-10-05 22:12:23,581] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:25,804] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /CloudNet/cloudnet/ HTTP/1.1" 200 52815
[2021-10-05 22:12:26,216] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:33,970] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/organization/ HTTP/1.1" 200 113073
[2021-10-05 22:12:34,146] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:37,477] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/organization/379/change/ HTTP/1.1" 200 31601
[2021-10-05 22:12:37,514] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/select2/i18n/zh-CN.js HTTP/1.1" 200 768
[2021-10-05 22:12:37,515] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/inlines.js HTTP/1.1" 200 15225
[2021-10-05 22:12:37,526] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[2021-10-05 22:12:37,661] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:12:39,396] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=crm&model_name=organization&field_name=Park HTTP/1.1" 200 313
[2021-10-05 22:12:40,259] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=crm&model_name=organization&field_name=Park HTTP/1.1" 200 313
[2021-10-05 22:12:44,400] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /crm/organization/379/change/ HTTP/1.1" 302 0
[2021-10-05 22:12:44,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/organization/ HTTP/1.1" 200 113281
[2021-10-05 22:12:45,172] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:27,402] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/oblist/ HTTP/1.1" 200 417163
[2021-10-05 22:13:27,435] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1454
[2021-10-05 22:13:27,580] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:31,156] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/contacts/ HTTP/1.1" 200 60654
[2021-10-05 22:13:31,333] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:32,728] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/contacthistory/ HTTP/1.1" 200 57695
[2021-10-05 22:13:32,882] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:45,678] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/miracleorders/ HTTP/1.1" 200 46208
[2021-10-05 22:13:45,861] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:46,948] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/miraclecredit/ HTTP/1.1" 200 29703
[2021-10-05 22:13:47,124] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:13:48,242] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/miraclebill/ HTTP/1.1" 200 45368
[2021-10-05 22:13:48,411] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:14:13,782] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/organization/379/change/ HTTP/1.1" 200 31531
[2021-10-05 22:14:13,952] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:14:16,142] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=crm&model_name=organization&field_name=Park HTTP/1.1" 200 313
[2021-10-05 22:14:19,679] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/organization/ HTTP/1.1" 200 113073
[2021-10-05 22:14:19,858] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:14:27,771] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /auth/user/ HTTP/1.1" 200 43128
[2021-10-05 22:14:27,791] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[2021-10-05 22:14:27,812] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[2021-10-05 22:14:27,948] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:14:29,233] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /auth/group/ HTTP/1.1" 200 29792
[2021-10-05 22:14:29,405] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:15:07,610] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:15:07,812] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:15:08,228] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:15:08,266] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:15:08,277] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-05 22:15:10,784] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:15:11,020] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:15:11,601] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:15:11,620] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:15:11,634] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-10-05 22:15:13,951] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 25236
[2021-10-05 22:15:14,579] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 52170
[2021-10-05 22:15:14,770] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:15:17,837] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parkmanager/ HTTP/1.1" 200 38291
[2021-10-05 22:15:18,004] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:15:18,098] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/parklog/ HTTP/1.1" 200 42868
[2021-10-05 22:15:18,500] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:16:22,149] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=1 HTTP/1.1" 200 52989
[2021-10-05 22:16:22,339] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:16:31,724] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/add/?_changelist_filters=o%3D1 HTTP/1.1" 200 36405
[2021-10-05 22:16:31,921] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:16:47,636] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /autocomplete/?app_label=Park&model_name=park&field_name=PM HTTP/1.1" 200 87
[2021-10-05 22:16:50,407] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /Park/park/add/?_changelist_filters=o%3D1 HTTP/1.1" 302 0
[2021-10-05 22:16:50,799] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=1 HTTP/1.1" 200 55287
[2021-10-05 22:16:51,007] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:16:53,682] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/GetTown/?id=6&Address=%E4%B8%8A%E6%B5%B7%E5%B8%82%E9%93%B6%E5%9F%8E%E4%B8%AD%E8%B7%AF29%E5%8F%B7 HTTP/1.1" 200 45
[2021-10-05 22:16:59,054] [log.py:224] [log:log_response] [WARNING]- Not Found: /Park/street/
[2021-10-05 22:16:59,055] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /Park/street/ HTTP/1.1" 404 8661
[2021-10-05 22:17:00,917] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/ HTTP/1.1" 200 54080
[2021-10-05 22:17:01,076] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:17:05,949] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=1 HTTP/1.1" 200 54925
[2021-10-05 22:17:06,127] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:17:09,046] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=2.1 HTTP/1.1" 200 55690
[2021-10-05 22:17:09,443] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-05 22:17:10,816] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Park/park/?o=5.2.1 HTTP/1.1" 200 56334
[2021-10-05 22:17:11,010] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /jsi18n/ HTTP/1.1" 200 8398
[2021-10-06 11:36:16,645] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-06 11:36:16,664] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-06 11:36:16,966] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
[2021-10-06 11:36:17,056] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Park\models.py changed, reloading.
